### ISSUE TITLE
Stubborn "attribute 'currentSystem' missing" error

### ISSUE THREAD

**Issue by cmatthias** [ahbnr/nixos-06cb-009a-fingerprint-sensor#1] opened 2023-02-12 20:14 UTC
Hi there, I have a T480 running NixOS on which it would be lovely to have fingerprint sensor functionality, and came across this repo. I seem to be running into this error no matter what I do:

```
# nixos-rebuild switch
building the system configuration...
error: attribute 'currentSystem' missing

       at /nix/store/cl52nkg25w301az0fygvp55j1x3g5wxf-source/pkgs/top-level/impure.nix:17:43:

           16|   # (build, in GNU Autotools parlance) platform.
           17|   localSystem ? { system = args.system or builtins.currentSystem; }
             |                                           ^
           18|
(use '--show-trace' to show detailed location information)
```

My understanding is that this means Nix doesn't know what system I'm building for, and since builtins.currentSystem is not defined for (pure) flakes, it blows up. This is confirmed by running `nixos-rebuild` with the `--impure` flag, which works great. But I would prefer not to have to pass that flag.

My `flake.nix`:

```{
  description = "NixOS configuration with flakes";
  
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-22.11";
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    fpsensor = {
      url = "github:ahbnr/nixos-06cb-009a-fingerprint-sensor";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, ... }@inputs:
  let
    system = "x86_64-linux";
    pkgs = import inputs.nixpkgs {
      inherit system;
      config.allowUnfree = true;
    };
  in {
    nixosConfigurations.colin-thinkpad = inputs.nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        inputs.home-manager.nixosModules.home-manager
        inputs.nixos-hardware.nixosModules.lenovo-thinkpad-t480
        inputs.fpsensor.nixosModules.open-fprintd
        inputs.fpsensor.nixosModules.python-validity
        ./configuration.nix 
      ];
    };
  };
}
```

And in `configuration.nix`, I have:

```
  services.open-fprintd.enable = true;
  services.python-validity.enable = true;
```

I'm a newbie to flakes so it's possible I'm doing something wrong here, but as you can see from my `flake.nix` I'm running home-manager via a flake also, and I have not seen this error at all with that flake. I confirmed this by commenting out only the fingerprint sensor modules in flake.nix's `modules` and the 2 `services` lines in configuration.nix, and everything built fine.

Is it possible there's a bug somewhere in this flake that might be causing my problem? Thanks in advance!

**Comment by ahbnr** [comment] 2023-02-12 20:20
> Is it possible there's a bug somewhere in this flake that might be causing my problem?

Yes, that is very much possible.
I am using "--impure" myself due to some other circumstances and that is probably why I did not encounter this issue.

I am also very much a complete newbie to NixOS and flakes but I will try to find out where the problem is coming from.

**Comment by ahbnr** [comment] 2023-02-12 21:50
@cmatthias I made some small changes in a separate branch, and the issue might be fixed now.
However, I can't test the changes right now but will do so later next week.

In any case, if you want to, you can already test out the change yourself by switching to the branch:
```nix
fpsensor = {
  url = "github:ahbnr/nixos-06cb-009a-fingerprint-sensor/fix-pure-mode-usage";
  inputs.nixpkgs.follows = "nixpkgs";
};
```

**Comment by cmatthias** [comment] 2023-02-12 23:20
@ahbnr This worked perfectly -- thank you for fixing it so quickly!

**Closed** 2023-02-13 19:29 UTC

**Comment by ahbnr** [comment] 2023-02-13 19:35
It also still works on my system with `--impure` so I merged the changes into the main branch am closed this issue.
Please don't hesitate to open another issue, if you stumble upon another problem.
